import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import DashboardSidebar from "./ui/partials/dashboard-sidebar";
import DashboardHeader from "./ui/partials/dashboard-header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function DashboardLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="relative flex min-h-screen w-full">
            {/* <div className="absolute z-10 w-full max-w-[250px] bg-purple-400 sm:static md:w-[30%]"> */}
            <div className="absolute left-0 top-0 z-10 flex w-[100px] max-w-[250px] justify-center bg-white sm:static md:w-[20%] lg:w-[25%]">
              <DashboardSidebar />
            </div>
            <div className="relative flex flex-1 flex-col">
              <DashboardHeader />
              <div className="flex flex-1 flex-col px-[5%] py-5 sm:py-6">
                {children}
              </div>
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
