import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import HeaderBar from "./ui/partials/header-bar";
import FooterBar from "./ui/partials/footer-bar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="relative flex flex-col">
            <HeaderBar />
            <div className="mx-auto w-full max-w-[90%] flex-1">{children}</div>
            <FooterBar />
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
